version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
  
  restgistry:
    image: gerardojunior/nodejs:stable
    restart: on-failure
    container_name: restgistry
    env_file:
      - .env
    volumes:
      - .:/src
    # ports:
      # - 3000:3000
    links:
      - db
    depends_on:
      - db


volumes:
  db-data:
    name: 'restgistry-db'